fails:Thread#kill can be rescued by outer rescue clause when inner ensure clause raises exception
